<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="RetroMesh.Engine">
      <HintPath>$(RetroMeshEnginePath)</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheOmegaStrain.Common\TheOmegaStrain.Common.csproj" />
    <ProjectReference Include="..\TheOmegaStrain.Domain\TheOmegaStrain.Domain.csproj" />
    <ProjectReference Include="..\TheOmegaStrain.Gameplay\TheOmegaStrain.Gameplay.csproj" />
    <ProjectReference Include="..\TheOmegaStrain.Game\TheOmegaStrain.Game.csproj" />
  </ItemGroup>
</Project>
