<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <RootNamespace>TheOmegaStrain.Benchmarks</RootNamespace>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="Microsoft.VisualStudio.DiagnosticsHub.BenchmarkDotNetDiagnosers" Version="18.3.36812.1" />
    <Reference Include="RetroMesh.Engine">
      <HintPath>$(RetroMeshEnginePath)</HintPath>
    </Reference>
    <Reference Include="RetroMesh.Rendering.Direct3D11">
      <HintPath>$(RetroMeshDirect3D11Path)</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TheOmegaStrain.Runtime\TheOmegaStrain.Runtime.csproj" />
    <ProjectReference Include="..\TheOmegaStrain.Wpf\TheOmegaStrain.Wpf.csproj" />
    <ProjectReference Include="..\TheOmegaStrain.Common\TheOmegaStrain.Common.csproj" />
  </ItemGroup>
</Project>
